### PR TITLE
build: add docker file

### PR DESCRIPTION
**Pull request by maicss**
Add docker file.
I can't find docker file in all official repositories, I don't know which the best way is to build a nuxt project to a docker image.
So I add dockerfile to this repo and tested:
- with node:alpine image size ~ 150mb
- with node:slim image size ~216mb

But there are two points I am not satisfied with this config:
- I am not sure this is the best way to build a nuxt project. Ie: build project in a folder and move the output to a new folder, and delete previous one.
- with non-root user, the image size reached to 1.2gb.

Anyone who can help with this PR is welcome!

### CODE REVIEW

**Comment by Atinux** [comment]
Hi @maicss 

You don't need Docker to build a Nuxt project actually

**Comment by maicss** [comment]
Sorry I don't understand. If I write an application, and I want to release a distribute to others,  what's the best way to do that?

Like a local file manager, not a website.

**Comment by Atinux** [comment]
I would say you share a git repository hosted on GitHub, GitLab, Bitbucket, etc.

**Comment by maicss** [comment]
My application needs to access user's local file or database, not a public website.

**Pull request closed without merging**
